# Sidebar navigation

- label: 'Основы web'
  link: '/base/web'
- label: Javascript
  link: '/front-end/javascript'
  items:
    - label: 'Теория JS'
      link: '/front-end/javascript/about'
    - label: 'Синтаксис JS'
      link: '/front-end/javascript'
    - label: 'Асинхронный JS'
      link: '/front-end/javascript/async'  
- label: Задачи Javascript
  items:  
   - label: 'LeedCode'
     link: '/tasks/leedcode'  
- label: 'React'
  items:
    - label: 'Теория React'
      link: '/front-end/react'
    - label: 'Хуки'
      link: '/front-end/react/hooks'    
- label: 'TypeScript'
  items:
  - label: 'Вопросы TypeScript'
    link: '/front-end/typescript'
- label: Больше
  items:
    - label: 'SOLID'
      link: '/more/solid'
    - label: 'UI/UX'
      link: '/more/ui-ux'
